name: Check file size
on:
  push:
  # to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Check large files
        uses: ppremk/lfs-warning@v3.3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          filesizelimit: 10MB # this is 10MB so we can sync to HF Spaces
