name: Check file size
on:
  push:
  # to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: read
  actions: write

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - name: Check large files
        uses: ppremk/lfs-warning@v3.3
        with:
          filesizelimit: 10MB # this is 10MB so we can sync to HF Spaces
